### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by biemond** [ianchesal/packer-config#18]
Hi,

Because I want to do some some advanced tests and cannot not do vbox inside vbox or qemu ( becuase of x86 vmx) and I don't have vmware workstation which can do this. 
 
So I test your great gem besides mac also on windows laptop, this works great but the only thing I need to do is removing the LoweredExpectations https://github.com/ianchesal/packer-config/blob/master/lib/packer-config.rb#L174
and its require https://github.com/ianchesal/packer-config/blob/master/lib/packer-config.rb#L11

I know it is on the todo list of LoweredExpectations  but I think it is easy to replace it by something else

Hopefully you have a fix for this.

**Comment by ianchesal** [comment]
Can you please try this branch on Windows and tell me if it solves the problem for you?

https://github.com/ianchesal/packer-config/tree/feature/windows

Thanks.

**Comment by ianchesal** [comment]
Did you have a chance to test that branch?

**Comment by biemond** [comment]
Will do it tomorrow .

Thanks

**Comment by biemond** [comment]
It working perfectly

**Comment by ianchesal** [comment]
The 1.6.0 release of `packer-config` contains these changes and is now live on rubygems.com
