### ISSUE TITLE
Readme example - Validation Error

### ISSUE THREAD

**Issue by frasercobb** [ianchesal/packer-config#2]
An error is raised during validation using the example in the readme.
Packer-config version: 0.0.4 && 0.0.3
Ruby version: 2.2.0

Example used: "Packing a Vagrant Basebox from a CentOS ISO Using VirtualBox"

Error:
http://puu.sh/ga1nL/df5ce0774f.png

**Comment by ianchesal** [comment]
Make sure you have packer in your path. You also need Vagrant and VirtualBox installed. See just-pushed commit for an updated integration test and README file that use CentOS 6.6. Works here.

**Comment by frasercobb** [comment]
My error was an incorrectly named script file causing the packer validate command to fail. Thanks for the help.

**Comment by ianchesal** [comment]
The error output from Packer should have been in the message for the exception that's raised. That's the right place for it.
