### ISSUE TITLE
RuboCop fails

### ISSUE THREAD

**Issue by mrjcleaver** [ianchesal/packer-config#22]
`martincleaver@MartinCleaversMBP-5.local:~/SoftwareDevelopment 13:50:45 513$ git clone https://github.com/ianchesal/packer-config.git
Cloning into 'packer-config'...
remote: Counting objects: 940, done.
remote: Total 940 (delta 0), reused 0 (delta 0), pack-reused 940
Receiving objects: 100% (940/940), 158.31 KiB | 0 bytes/s, done.
Resolving deltas: 100% (550/550), done.
Checking connectivity... done.
martincleaver@MartinCleaversMBP-5.local:~/SoftwareDevelopment 13:50:51 514$ cd packer-config/
martincleaver@MartinCleaversMBP-5.local:~/SoftwareDevelopment/packer-config 13:50:54 515$ ls
COPYRIGHT             LICENSE               RELEASENOTES.md       TODO.md               packer-config.gemspec tasks
Gemfile               README.md             Rakefile              lib                   spec
martincleaver@MartinCleaversMBP-5.local:~/SoftwareDevelopment/packer-config 13:50:54 516$ rake
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/Volumes/Storage/martincleaver/SoftwareDevelopment/packer-config/tasks/rspec.rake:1:in `<top (required)>'
(See full trace by running task with --trace)
martincleaver@MartinCleaversMBP-5.local:~/SoftwareDevelopment/packer-config 13:51:00 517$ bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Installing rake 10.5.0
Installing ast 2.3.0
Using bundler 1.13.0.rc.1
Installing diff-lcs 1.2.5
Installing fakefs 0.9.1
Using packer-config 1.6.0 from source at `.`
Installing powerpack 0.1.1
Installing rainbow 2.1.0
Installing rspec-support 3.5.0
Installing ruby-progressbar 1.8.1
Installing unicode-display_width 1.1.0
Installing rubygems-tasks 0.2.4
Installing parser 2.3.1.2
Installing rspec-core 3.5.3
Installing rspec-expectations 3.5.0
Installing rspec-mocks 3.5.0
Installing rubocop 0.42.0
Installing rspec 3.5.0
Bundle complete! 8 Gemfile dependencies, 18 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
martincleaver@MartinCleaversMBP-5.local:~/SoftwareDevelopment/packer-config 13:51:28 518$ rake
Running RuboCop...
Warning: unrecognized cop Style/DeprecatedHashMethods found in /Volumes/Storage/martincleaver/SoftwareDevelopment/packer-config/.rubocop_todo.yml
Warning: unrecognized cop Style/DeprecatedHashMethods found in /Volumes/Storage/martincleaver/SoftwareDevelopment/packer-config/.rubocop.yml
Inspecting 71 files
...........CCCC...C............C.C.....................................

Offenses:

lib/packer/dataobject.rb:28:14: C: Style/NumericPredicate: Use (r.length - (r - self.data.keys).length).zero? instead of r.length - (r - self.data.keys).length == 0.
          if r.length - (r - self.data.keys).length == 0
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/packer/dataobject.rb:44:34: C: Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?.
        if self.key_dependencies.has_key? data_key
                                 ^^^^^^^^
lib/packer/dataobject.rb:71:22: C: Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?.
        if self.data.has_key? e
                     ^^^^^^^^
lib/packer/envvar.rb:4:5: C: Style/MethodMissing: When using method_missing, define respond_to_missing? and fall back on super.
    def method_missing(method_name, *args) ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/packer/macro.rb:4:5: C: Style/MethodMissing: When using method_missing, define respond_to_missing? and fall back on super.
    def method_missing(method_name, *args) ...
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/packer/postprocessor.rb:47:24: C: Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?.
      unless self.data.has_key? 'only'
                       ^^^^^^^^
lib/packer/postprocessor.rb:54:24: C: Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?.
      unless self.data.has_key? 'except'
                       ^^^^^^^^
lib/packer/provisioner.rb:65:24: C: Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?.
      unless self.data.has_key? 'only'
                       ^^^^^^^^
lib/packer/provisioner.rb:72:24: C: Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?.
      unless self.data.has_key? 'except'
                       ^^^^^^^^
lib/packer/provisioner.rb:84:24: C: Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?.
      unless self.data.has_key? 'override'
                       ^^^^^^^^
lib/packer/provisioner.rb:87:20: C: Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?.
      if self.data.has_key? @data['override'][builddefinition]
                   ^^^^^^^^
lib/packer/runner.rb:38:54: C: Style/NumericPredicate: Use status.zero? instead of status == 0.
      raise CommandExecutionError.new(stderr) unless status == 0
                                                     ^^^^^^^^^^^
lib/packer-config.rb:156:29: C: Style/PreferredHashMethods: Use Hash#key? instead of Hash#has_key?.
      unless self.variables.has_key? name
                            ^^^^^^^^

71 files inspected, 13 offenses detected
RuboCop failed!
martincleaver@MartinCleaversMBP-5.local:~/SoftwareDevelopment/packer-config 13:51:37 519$ ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin14.0]
martincleaver@MartinCleaversMBP-5.local:~/SoftwareDevelopment/packer-config 13:53:09 520$ 
`

**Comment by ianchesal** [comment]
Sounds like Rubocop's defaults have been updated since this gem was last released and there are some changes. We do fuzzy matching against development dependencies (see https://github.com/ianchesal/packer-config/blob/master/Gemfile) so any version of Rubcop < 1.0 is valid. I know some of those warnings like the check for `.zero?` are fairly new defaults in Rubocop.

The project needs an update for the latest Rubocop defaults. Either the code needs to change to align with the new defaults or exceptions need to be added. And it looks like `Style/DeprecatedHashMethods` needs to be removed from the rule files for the project.

**Comment by ianchesal** [comment]
This is fixed on the `develop` branch not. Changes won't be available on `master` until the next major release.

**Comment by ianchesal** [comment]
The Rubocop checks pass now: https://travis-ci.org/ianchesal/packer-config/builds/158373844
