### ISSUE TITLE
Integration test fails

### ISSUE THREAD

**Issue by mrjcleaver** [ianchesal/packer-config#23]
Not sure why, as the Travis test is passing, but the integration test failed for me:

`martincleaver@MartinCleaversMBP-5.local:~/SoftwareDevelopment/packer-config 14:09:11 553$     bundle exec rake test:integration
/Volumes/Storage/martincleaver/.rbenv/versions/2.1.1/bin/ruby -I/Volumes/Storage/martincleaver/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/lib:/Volumes/Storage/martincleaver/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-support-3.5.0/lib /Volumes/Storage/martincleaver/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/rspec-core-3.5.3/exe/rspec --pattern spec/integration/\*\*/\*_spec.rb
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://mirrors.sonic.net/centos//6.7/isos/x86_64/CentOS-6.7-x86_64-bin-DVD1.iso
    virtualbox-iso: Error downloading: checksums didn't match expected: 7bb8c1c23a4fdef93e6f0a6347d570e5764d0b38
==> virtualbox-iso: ISO download failed.
Build 'virtualbox-iso' errored: ISO download failed.

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: ISO download failed.

==> Builds finished but no artifacts were created.
F

Failures:

  1) Packer::Config can build a centos-6.5 Vagrant base box
     Failure/Error: expect(pconfig.build).to be_truthy
     Packer::Config::PackerBuildError:
     # ./lib/packer-config.rb:113:in `rescue in block in build'
     # ./lib/packer-config.rb:110:in `block in build'
     # ./lib/packer-config.rb:109:in `chdir'
     # ./lib/packer-config.rb:109:in `build'
`

**Comment by ianchesal** [comment]
Looks like CentOS 6.7 has gone away from that mirror: http://mirrors.sonic.net/centos/6.7/readme

Project needs an update to pull the ISO from a new mirror so this test functions.

**Comment by ianchesal** [comment]
This is fixed on the `develop` branch not. Changes won't be available on `master` until the next major release.
